### ISSUE TITLE
How can I install it on my Mi Band?

### ISSUE THREAD

**Issue by ny0510** [Dustbin-lst/BandTOTP-Band#1]

**Comment by leset0ng** [comment]
download Notify for Xiaomi from Google Play or Huawei Appgalley
and follow the indtruction to bind your band
go to devices page, and see the install firmware button
then,install third-party app

sry for bad english

**Comment by OnDriveLine** [comment]
And I'd like to tell you that in global version, the devices may bot support this quickapp since by it lack if the interconnect feature. Maybe you can ask for the modified mi fitness author's help.
tg channel: @mi_watch_int
